sudo: required

language: go
go:
  - "1.10.3"

services:
  - docker

before_install:
  - docker pull contribsys/faktory:latest
  - docker run -d -p 127.0.0.1:7419:7419 -p 127.0.0.1:7420:7420 contribsys/faktory:latest /faktory -b :7419 -w :7420
  - docker ps -a

install: go get -t ./...
